### ISSUE TITLE
Same input file results in different binaries

### ISSUE THREAD

**Issue by schusterro** [CherryPerry/GradleFileEncrypt#47]
I have noticed that the plugin outputs different binaries, but with same file size, even if the input files remain the same.
Why does it do that? It makes keeping track of changes even harder like this. Can't the encryption be changed to always produce the same file?

**Comment by CherryPerry** [comment]
The issue source is described [here](https://github.com/CherryPerry/GradleFileEncrypt/blob/master/src/test/kotlin/com/cherryperry/gfe/FileEncryptPluginFunctionalTest.kt#L220-L226).

For now have 2 ideas:
1. Create a snapshot of input files before running `EncryptTask` but not sure if it will end up in the plugin because of its hacky nature.
2. Provide a seed to `Random` for IV generation based on file name to make IV deterministic per file.

Will play a little bit more, so do not expect the fast fix please.
